services:
  mysql:
    image: mysql:5.7
    container_name: crudgo
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 3306:3306