version: '3'

networks:
  firstcrud_network:

services:
  mysql:
    image: mysql:5.7
    container_name: crudgo
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3306:3306"
    networks:
      - firstcrud_network

  firstcrud:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - "8000:8000" 
    depends_on:
      - mysql
    networks:
      - firstcrud_network
