version: '3'

networks:
  firstcrud_network:

services:
  mysql:
    image: mysql:5.7
    container_name: crudgo
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3306:3306"
    networks:
      - firstcrud_network

  firstcrud:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      DB_DRIVER: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: crudgo
      WEB_SERVER_PORT: 8000
      JWT_SECRET: 0ecbc0de-a73b-429c-bb0f-e23620dbcd79
      JWT_EXPIRES_IN: 24
    restart: always
    ports:
      - "8000:8000" 
    depends_on:
      - mysql
    networks:
      - firstcrud_network
